server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: ecom-pulse

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - docker:
          auto_extract_kubernetes_metadata: false
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: ".*_(.*)_.*"
        target_label: container